version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: catalog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TokyoTokyo123321
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
    volumes:
      - catalog_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: localhost

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: TokyoTokyo123321

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  catalog_pg_data: